"""'Init'

Revision ID: 6465872379f4
Revises: b5c108fc6952
Create Date: 2023-03-30 21:37:34.538658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6465872379f4'
down_revision = 'b5c108fc6952'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
