"""'First'

Revision ID: 69eaf77e4c62
Revises: 6837e32a929a
Create Date: 2023-04-02 20:05:44.312427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eaf77e4c62'
down_revision = '6837e32a929a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('teachers', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('teachers', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('teachers', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
