# Generated by Django 4.2 on 2023-05-22 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_userprofile_avatar_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserAvatar',
        ),
    ]
