# Generated by Django 4.2 on 2023-04-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='picture',
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
