# Generated by Django 4.2 on 2023-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_picture_author_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
